export const words = [
    {
        id: 0,
        name: 'human',
        rus_name: 'Человек',
        date: '2022-03-23',
        data: [
            {
                id: 11350,
                word: 'arm',
                transcription: '[ ɑ:m ]',
                value: 'рука',
                tags: 'часть тела',
                tags_json: '["u0447u0430u0441u0442u044c u0442u0435u043bu0430"]',
            },
            {
                id: 12087,
                word: 'abdomen',
                transcription: '[ ˈæbdəmən ]',
                value: 'живот',
                tags: 'анатомия',
                tags_json: '["u0430u043du0430u0442u043eu043cu0438u044f"]',
            },
            {
                id: 12088,
                word: 'ankle',
                transcription: '[ ˈæŋkl̩ ]',
                value: 'голеностоп',
                tags: 'анатомия',
                tags_json: '["u0430u043du0430u0442u043eu043cu0438u044f"]',
            },
            {
                id: 12089,
                word: 'appendix',
                transcription: '[ əˈpendɪks ]',
                value: 'аппендикс',
                tags: 'анатомия',
                tags_json: '["u0430u043du0430u0442u043eu043cu0438u044f"]',
            },
            {
                id: 12091,
                word: 'artery',
                transcription: '[ ˈɑːtəri ]',
                value: 'артерия',
                tags: 'анатомия',
                tags_json: '["u0430u043du0430u0442u043eu043cu0438u044f"]',
            },
            {
                id: 12092,
                word: 'backbone',
                transcription: '[ ˈbækbəʊn ]',
                value: 'позвоночник',
                tags: 'анатомия',
                tags_json: '["u0430u043du0430u0442u043eu043cu0438u044f"]',
            },
            {
                id: 12093,
                word: 'biceps',
                transcription: '[ ˈbaɪseps ]',
                value: 'бицепс',
                tags: 'анатомия',
                tags_json: '["u0430u043du0430u0442u043eu043cu0438u044f"]',
            },
            {
                id: 12094,
                word: 'bowels',
                transcription: '[ ˈbaʊəlz ]',
                value: 'кишечник',
                tags: 'анатомия',
                tags_json: '["u0430u043du0430u0442u043eu043cu0438u044f"]',
            },
            {
                id: 12095,
                word: 'brain',
                transcription: '[ breɪn ]',
                value: 'мозг',
                tags: 'анатомия',
                tags_json: '["u0430u043du0430u0442u043eu043cu0438u044f"]',
            },
            {
                id: 12118,
                word: "finger",
                transcription: "[ˈfɪŋɡə]",
                value: "палец",
                tags: "анатомия",
                tags_json: "[\"u0430u043du0430u0442u043eu043cu0438u044f\"]"
            },

        ],
    },
    {
        id: 1,
        name: 'nature',
        rus_name: 'Природа',
        date: '2022-04-01',
        data: [
            {
                id: 11354,
                word: 'air',
                transcription: '[eər]',
                value: 'воздух',
                tags: 'природа',
                tags_json: '["u043fu0440u0438u0440u043eu0434u0430"]',
            },
            {
                id: 11355,
                word: 'sun',
                transcription: '[sʌn]',
                value: 'солнце',
                tags: 'природа',
                tags_json: '["u043fu0440u0438u0440u043eu0434u0430"]',
            }, {
                id: 11356,
                word: 'moon',
                transcription: '[muːn]',
                value: 'луна',
                tags: 'природа',
                tags_json: '["u043fu0440u0438u0440u043eu0434u0430"]',
            },
            {
                id: 11357,
                word: 'summer',
                transcription: '[ˈsʌmər]',
                value: 'лето',
                tags: 'время года',
                tags_json: '["u0432u0440u0435u043cu044f u0433u043eu0434u0430"]',
            },
            {
                id: 11358,
                word: 'autumn',
                transcription: '[ˈɔːtəm]',
                value: 'осень',
                tags: 'время года',
                tags_json: '["u0432u0440u0435u043cu044f u0433u043eu0434u0430"]',
            },
            {
                id: 11359,
                word: 'winter',
                transcription: '[ˈwɪntə]',
                value: 'зима',
                tags: 'время года',
                tags_json: '["u0432u0440u0435u043cu044f u0433u043eu0434u0430"]',
            },
            {
                id: 11360,
                word: 'spring',
                transcription: '[sprɪŋ]',
                value: 'весна',
                tags: 'время года',
                tags_json: '["u0432u0440u0435u043cu044f u0433u043eu0434u0430"]',
            },
            {
                id: 11361,
                word: ' flower',
                transcription: '[ˈflaʊə]',
                value: 'цветок',
                tags: 'растения',
                tags_json: '[]',
            },
            {
                id: 12084,
                word: 'palm',
                transcription: '[pa:m]',
                value: 'пальма',
                tags: 'деревья',
                tags_json: '["u0434u0435u0440u0435u0432u044cu044f"]',
            },
            {
                id: 12085,
                word: 'bay',
                transcription: '[bei]',
                value: 'лавр',
                tags: 'деревья',
                tags_json: '["u0434u0435u0440u0435u0432u044cu044f"]',
            },
            {
                id: 12086,
                word: 'larch',
                transcription: '[la:t∫]',
                value: 'лиственница',
                tags: 'деревья',
                tags_json: '["u0434u0435u0440u0435u0432u044cu044f"]',
            },
        ],
    },
    {
        id: 2,
        name: 'animals',
        rus_name: 'Животные',
        date: '2022-05-15',
        data: [
            {
                id: 11448,
                word: 'cat ',
                transcription: '[kæt]',
                value: 'кот',
                tags: 'животное',
                tags_json: '["u0436u0438u0432u043eu0442u043du043eu0435"]',
            },
            {
                id: 11449,
                word: 'dog',
                transcription: '[dɒɡ]',
                value: 'собака',
                tags: 'животное',
                tags_json: '["u0436u0438u0432u043eu0442u043du043eu0435"]',
            },
            {
                id: 11953,
                word: 'platypus',
                transcription: '[ˈplætɪpəs]',
                value: 'утконос',
                tags: 'животное',
                tags_json: '["u0440u044bu0431u044b"]',
            },
            {
                id: 11951,
                word: 'turbot brill',
                transcription: '[ˈtɜːbət brɪl]',
                value: 'камбала',
                tags: 'рыбы',
                tags_json: '["u0440u044bu0431u044b"]',
            },
            {
                id: 11952,
                word: 'ramp',
                transcription: '[ræmp]',
                value: 'скат',
                tags: 'рыбы',
                tags_json: '["u0440u044bu0431u044b"]',
            },

        ],
    },
    {
        id: 3,
        name: 'art',
        rus_name: 'Искусство',
        date: '2022-07-23',
        data: [

            {
                id: 11997,
                word: 'flute',
                transcription: '[fluːt]',
                value: 'флейта',
                tags: 'музыка',
                tags_json: '["u043cu0443u0437u044bu043au0430"]',
            },
            {
                id: 11998,
                word: 'grand piano',
                transcription: '[grænd pɪˈænəʊ]',
                value: 'рояль',
                tags: 'музыка',
                tags_json: '["u043cu0443u0437u044bu043au0430"]',
            },
            {
                id: 11999,
                word: 'guitar',
                transcription: '[gɪˈtɑː]',
                value: 'гитара',
                tags: 'музыка',
                tags_json: '["u043cu0443u0437u044bu043au0430"]',
            },
            {
                id: 12000,
                word: 'harp',
                transcription: '[hɑːp]',
                value: 'арфа',
                tags: 'музыка',
                tags_json: '["u043cu0443u0437u044bu043au0430"]',
            },
        ],
    },
    {
        id: 4,
        name: "science",
        rus_name: "Наука",
        date: "2022-08-23",
        data: [
            {
                id: 11949,
                word: 'neon',
                transcription: '[ ˈniːɒn ]',
                value: 'неон',
                tags: 'химические элементы',
                tags_json: '["u0445u0438u043cu0438u0447u0435u0441u043au0438u0435 ' +
                    'u044du043bu0435u043cu0435u043du0442u044b"]',
            },
            {
                id: 11950,
                word: 'domestic market',
                transcription: '[ dəˈmestɪk ˈmɑːkɪt ]',
                value: 'внутренний рынок',
                tags: 'экономика',
                tags_json: '["u044du043au043eu043du043eu043cu0438u043au0430"]',
            },
            {
                id: 11995,
                word: 'mortgage',
                transcription: '[ ˈmɔːɡɪdʒ ]',
                value: 'ипотека',
                tags: 'экономика',
                tags_json: '["u044du043au043eu043du043eu043cu0438u043au0430"]',
            },
            {
                id: 11996,
                word: 'sodium',
                transcription: '[ ˈsəʊdɪəm ]',
                value: 'натрий',
                tags: 'химические элементы',
                tags_json: '["u0445u0438u043cu0438u0447u0435u0441u043au0438u0435 ' +
                    'u044du043bu0435u043cu0435u043du0442u044b"]',
            },
            {
                id: 12127,
                word: "readability",
                transcription: "[riːdəˈbɪlɪtɪ] ",
                value: "читабельность",
                tags: "IT",
                tags_json: "[\"IT\"]"
            },
            {
                id: 12130,
                word: "argument",
                transcription: "[ˈɑːgjʊmənt]",
                value: "аргумент",
                tags: "IT",
                tags_json: "[\"IT\"]"
            },
            {
                id: 12131,
                word: "restructuring",
                transcription: "[riːˈstrʌkʧərɪŋ]",
                value: "трансформация",
                tags: "IT",
                tags_json: "[\"IT\"]"
            },
            {
                id: 12134,
                word: "stack",
                transcription: "[stæk]",
                value: "стек",
                tags: "IT",
                tags_json: "[\"IT\"]"
            },
            {
                id: 12136,
                word: "hardware",
                transcription: "[ˈhɑːdwɛə]",
                value: "оборудование",
                tags: "IT",
                tags_json: "[\"IT\"]"
            },
            {
                id: 12154,
                word: "deployment",
                transcription: "[dɪˈplɔɪmənt]",
                value: "развертывание",
                tags: "технологии",
                tags_json: "[\"u0442u0435u0445u043du043eu043bu043eu0433u0438u0438\"]"
            }
        ]
    },
    {
        id: 5,
        name: 'colors',
        rus_name: 'Цвета',
        date: '2022-09-26',
        data: [
            {
                id: 12097,
                word: "red",
                transcription: "[red]",
                value: "красный",
                tags: "цвета",
                tags_json: "[\"u0446u0432u0435u0442u0430\"]"
            },
            {
                id: 12101,
                word: "orange",
                transcription: "[ˈɒrɪndʒ]",
                value: "оранжевый",
                tags: "цвета",
                tags_json: "[\"u0446u0432u0435u0442u0430\"]"
            },
            {
                id: 12104,
                word: "yellow",
                transcription: "[ˈjeləʊ]",
                value: "желтый",
                tags: "цвета",
                tags_json: "[\"u0446u0432u0435u0442u0430\"]"
            },
            {
                id: 12106,
                word: "green",
                transcription: "[ɡriːn]",
                value: "зеленый",
                tags: "цвета",
                tags_json: "[\"u0446u0432u0435u0442u0430\"]"
            },
            {
                id: 12074,
                word: 'turquoise',
                transcription: '[ ˈtɜːkwɔɪz ]',
                value: 'бирюзовый',
                tags: 'цвета',
                tags_json: 'null',
            },
            {
                id: 12077,
                word: 'pearl',
                transcription: '[pɜːl]',
                value: 'жемчужный',
                tags: 'цвета',
                tags_json: '["u0446u0432u0435u0442u0430"]',
            },
            {
                id: 12079,
                word: 'indigo',
                transcription: '[ˈɪndɪɡəʊ]',
                value: 'индиго',
                tags: 'цвета',
                tags_json: '["u0446u0432u0435u0442u0430"]',
            },
            {
                id: 12080,
                word: 'olive',
                transcription: '[ˈɒlɪv]',
                value: 'оливковый',
                tags: 'цвета',
                tags_json: '["u0446u0432u0435u0442u0430"]',
            },
            {
                id: 12081,
                word: 'sky blue',
                transcription: '[skaɪ bluː]',
                value: 'небесно-голубой',
                tags: 'цвета',
                tags_json: '["u0446u0432u0435u0442u0430"]',
            },
            {
                id: 12082,
                word: 'honeydew',
                transcription: '[ˈhʌnɪdjuː]',
                value: 'медовый',
                tags: 'цвета',
                tags_json: '["u0446u0432u0435u0442u0430"]',
            },
            {
                id: 12083,
                word: 'lime green',
                transcription: '[laɪm ɡriːn]',
                value: 'лимонно-зеленый',
                tags: 'цвета',
                tags_json: '["u0446u0432u0435u0442u0430"]',
            },
        ],
    },
];

export const groupCellNames = [
    {id: 'id', label: 'ID', isEditable: false},
    {id: 'rus_name', label: 'Название', isEditable: true},
    {id: 'numberOfCards', label: 'Кол-во слов', isEditable: false},
    {id: 'date', label: 'Дата', isEditable: false},
];
export const wordCellNames = [
    {id: 'id', label: 'ID', isEditable: false},
    {id: 'word', label: 'Слово', isEditable: true},
    {id: 'transcription', label: '[...]', isEditable: true},
    {id: 'value', label: 'Значение', isEditable: true},
    {id: 'tags', label: 'Теги', isEditable: true},
];
